version: "3.9"

services:
  vesteda:
    build: vesteda/
    environment:
      - MESSAGEBIRD_CLIENT=ABC
      - MESSAGEBIRD_DESTINATION=DEF
      - MESSAGEBIRD_ORIGINATOR=MessageBird
  redis:
    image: "redis:alpine"
