version: "3.9"

services:
  vesteda:
    build: vesteda/
    environment:
      - MESSAGEBIRD_CLIENT="${MESSAGEBIRD_CLIENT}"
      - MESSAGEBIRD_DESTINATION="${MESSAGEBIRD_DESTINATION}"
      - MESSAGEBIRD_ORIGINATOR="${MESSAGEBIRD_ORIGINATOR}"
  redis:
    image: "redis:alpine"
